# Generated by Django 2.2.4 on 2020-11-10 11:00

from django.db import migrations
import phonenumbers


def phonenumbers_parser(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            normal_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        # Если номер отсутствует или состоит из невалидных символов
        except phonenumbers.phonenumberutil.NumberParseException:
            flat.owner_pure_phone = ''
            flat.save()
        else:
            # проверяем на валидность
            if phonenumbers.is_valid_number(normal_phonenumber):
                flat.owner_pure_phone = '+' + str(normal_phonenumber.country_code) + str(normal_phonenumber.national_number)
            else:
                flat.owner_pure_phone = ''
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20201110_1356'),
    ]

    operations = [
        migrations.RunPython(phonenumbers_parser)
    ]
