# Generated by Django 2.2.4 on 2020-11-10 13:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20201110_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(default='default', max_length=20, verbose_name='Номер владельца'),
            preserve_default=False,
        ),
    ]
